// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalrMvc.Data;

#nullable disable

namespace SignalrMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018211623_AddUserAuthAndPrivateMessaging")]
    partial class AddUserAuthAndPrivateMessaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SignalrMvc.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_ChatMessages_SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("SignalrMvc.Models.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.HasIndex("ReceiverId", "IsRead");

                    b.HasIndex("SenderId", "ReceiverId", "SentAt");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("SignalrMvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsOnline");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 18, 23, 16, 20, 765, DateTimeKind.Local).AddTicks(4967),
                            Email = "alice@chat.com",
                            FullName = "Alice Johnson",
                            IsOnline = false,
                            PasswordHash = "$2a$11$5NH7miJjFp0mbvBrvrHxb.hIckRoKL.DDta8gwKgj9RI0UOc2wa5C",
                            ProfileImage = "https://ui-avatars.com/api/?name=Alice+Johnson&background=667eea&color=fff",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 18, 23, 16, 20, 765, DateTimeKind.Local).AddTicks(4973),
                            Email = "bob@chat.com",
                            FullName = "Bob Smith",
                            IsOnline = false,
                            PasswordHash = "$2a$11$5NH7miJjFp0mbvBrvrHxb.hIckRoKL.DDta8gwKgj9RI0UOc2wa5C",
                            ProfileImage = "https://ui-avatars.com/api/?name=Bob+Smith&background=764ba2&color=fff",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 18, 23, 16, 20, 765, DateTimeKind.Local).AddTicks(4976),
                            Email = "charlie@chat.com",
                            FullName = "Charlie Brown",
                            IsOnline = false,
                            PasswordHash = "$2a$11$5NH7miJjFp0mbvBrvrHxb.hIckRoKL.DDta8gwKgj9RI0UOc2wa5C",
                            ProfileImage = "https://ui-avatars.com/api/?name=Charlie+Brown&background=f093fb&color=fff",
                            Username = "charlie"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 18, 23, 16, 20, 765, DateTimeKind.Local).AddTicks(4978),
                            Email = "diana@chat.com",
                            FullName = "Diana Prince",
                            IsOnline = false,
                            PasswordHash = "$2a$11$5NH7miJjFp0mbvBrvrHxb.hIckRoKL.DDta8gwKgj9RI0UOc2wa5C",
                            ProfileImage = "https://ui-avatars.com/api/?name=Diana+Prince&background=4facfe&color=fff",
                            Username = "diana"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 18, 23, 16, 20, 765, DateTimeKind.Local).AddTicks(4981),
                            Email = "eve@chat.com",
                            FullName = "Eve Davis",
                            IsOnline = false,
                            PasswordHash = "$2a$11$5NH7miJjFp0mbvBrvrHxb.hIckRoKL.DDta8gwKgj9RI0UOc2wa5C",
                            ProfileImage = "https://ui-avatars.com/api/?name=Eve+Davis&background=43e97b&color=fff",
                            Username = "eve"
                        });
                });

            modelBuilder.Entity("SignalrMvc.Models.UserConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("SignalrMvc.Models.PrivateMessage", b =>
                {
                    b.HasOne("SignalrMvc.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SignalrMvc.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SignalrMvc.Models.UserConnection", b =>
                {
                    b.HasOne("SignalrMvc.Models.User", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SignalrMvc.Models.User", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
